controller_manager:
  ros__parametrs:
    update_rate: 100 #in hz

    motor_Joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

  motor_joint_state_broadcaster:
    ros__parametrs: {}

  motor_velocity_controller:
    ros2__parameters:
      joints:
        - base_motor_joint  #this name should match the joint name in URDF
      interface_name: velocity
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity