<?xml version="1.0"?>        <!-- to recognize the file as xml file, URDF uses metric system -->
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">        <!-- robot tag -->

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="caster_wheel_radius" value="${wheel_radius / 2}" />

    <material name="blue">  <!-- set colour name-->
        <color rgba="0 0 0.8 1" />
    </material>

    <material name="grey">  <!-- set colour name-->
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <link name="base_footprint" />    <!-- set base link name -->

    <link name="base_link">    <!-- set base link name -->
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />     <!-- set size -->
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">    <!-- set second link name -->
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />     <!-- set size -->
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />


    <link name="castor_wheel_link">    <!-- set second link name -->
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />     <!-- set size -->
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <joint name="footprint_base_joint" type="revolute">     <!-- set joint name and type-->
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" velocity="100" effort="100" />
    </joint>
    
    <joint name="base_right_wheel_joint" type="continuous">     <!-- set joint name and type-->
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4} ${-((base_width / 2) + (wheel_length / 2))} 0" rpy="${pi / 2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">     <!-- set joint name and type-->
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4} ${(base_width / 2) + (wheel_length / 2)} 0" rpy="${pi / 2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <joint name="base_castor_joint" type="fixed">     <!-- set joint name and type-->
        <parent link="base_link" />
        <child link="castor_wheel_link" />
        <origin xyz="${base_length / 3} 0 ${-caster_wheel_radius}" rpy="0 0 0" />
    </joint>


</robot>    


   

